language: go
go: 1.2
install: make deps
script: make ci
services:
- rabbitmq
notifications:
  hipchat:
    rooms:
      secure: "nonfW/JytEY1P++k39EfL9ck9V99jH6vONTGG9m6NjIH+VDrTl+lwBM2r9txRhfJnozYAxvkWQ/QrgIPqv5wJV6ZLHiSP8gxVGV7bPiaUBYh3CqpAzlAFBYMtvqmvXjofxRKxGi7qQPkyd1pxDFTeZM/nkohjkXisYksSBwZfoE="
    template:
    - '<img src="https://db.tt/K0gEyZVh">&nbsp;(%{repository_slug})&nbsp;<a href="%{build_url}">%{branch}</a>
      - <a href="%{compare_url}">%{commit}</a> : %{message}'
    format: html
