data_dir = "/var/lib/delayd"

[amqp]
url = "amqp://localhost"

[amqp.exchange]
name = "delayd"
kind = "topic"
durable = true
auto_delete = false
internal = false
noWait = false

[amqp.queue]
name = "delayd"
bind = [ "delayd" ]

durable = true
auto_ack = false
exclusive = false
no_local = false
no_wait = false
auto_delete = false

# args table is not covered here
